Jumpstart.config = Jumpstart::Configuration.new({"application_name" => "PressGo",
 "business_name" => "pressgo, llc",
 "business_address" => "Boston, MA",
 "domain" => "pressgo.tech",
 "support_email" => "hello@pressgo.tech",
 "default_from_email" => "PressGo <no-reply@pressgo.tech>",
 "background_job_processor" => "solid_queue",
 "email_provider" => "resend",
 "account_types" => "both",
 "apns" => false,
 "fcm" => false,
 "integrations" => [],
 "omniauth_providers" => [],
 "payment_processors" => [],
 "multitenancy" => [],
 "gems" => []})
